package system

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"

	"github.com/pi-sandbox/pi/pkg/runtime/detect"
)

// defaultConfigYAML is the minimal config written when none exists.
const defaultConfigYAML = `# Pi Sandbox configuration
# Generated by 'pi system doctor'. Edit to customize.

# Default runtime mode: fast | compat | secure | microvm
mode: fast

# Default exec timeout (seconds)
exec_timeout_s: 120

# Max exec output per call
max_output_bytes: 8388608  # 8 MiB

# Network mode: none | restricted | open
network_mode: none

# Context store path (leave empty for default ~/.pi-box/contexts.yaml)
contexts_path: ""
`

// requiredSystemCommands lists commands pi-sandbox relies on.
// Missing entries trigger a warning (not an error — optional components).
var requiredSystemCommands = []struct {
	cmd  string
	what string
}{
	{"git", "git clone/diff/patch operations"},
	{"tar", "artifact export"},
	{"find", "workspace scan"},
}

// Issue represents a single issue found by the doctor.
type Issue struct {
	Severity       string // "error", "warning", "info"
	Message        string
	Recommendation string
}

// DoctorResult holds the results of a doctor check.
type DoctorResult struct {
	Issues []Issue
	Passed bool
}

// RunDoctor performs all doctor checks (AC-16 / SPEC.md §7).
// Order: pi-home → dirs → config → permissions → system commands → daemon binary → runtimes.
func RunDoctor() *DoctorResult {
	result := &DoctorResult{}

	// ── Pi Box home ────────────────────────────────────────────────────────────
	piHome := PiHome()
	if !DirExists(piHome) {
		result.Issues = append(result.Issues, Issue{
			Severity:       "warning",
			Message:        fmt.Sprintf("Pi Box home directory does not exist: %s", piHome),
			Recommendation: "Initialize with 'pi system status' to create default directories",
		})
	} else {
		result.Issues = append(result.Issues, Issue{
			Severity: "info",
			Message:  fmt.Sprintf("Pi Box home directory: %s", piHome),
		})
	}

	// ── Required sub-directories ───────────────────────────────────────────
	for _, dir := range []string{"sandboxes", "templates", "caches"} {
		path := filepath.Join(piHome, dir)
		if DirExists(path) {
			result.Issues = append(result.Issues, Issue{
				Severity: "info",
				Message:  fmt.Sprintf("Directory exists: %s", dir),
			})
		} else {
			result.Issues = append(result.Issues, Issue{
				Severity:       "warning",
				Message:        fmt.Sprintf("Missing directory: %s", dir),
				Recommendation: "Will be created on first use",
			})
		}
	}

	// ── Config file ────────────────────────────────────────────────────────
	// AC-16: pi system doctor validates configuration; creates default if missing.
	configPath := filepath.Join(piHome, "config.yaml")
	if _, err := os.Stat(configPath); err == nil {
		data, readErr := os.ReadFile(configPath)
		if readErr != nil || len(data) == 0 {
			result.Issues = append(result.Issues, Issue{
				Severity:       "warning",
				Message:        "Config file exists but is unreadable",
				Recommendation: fmt.Sprintf("Check permissions: %s", configPath),
			})
		} else {
			result.Issues = append(result.Issues, Issue{
				Severity: "info",
				Message:  fmt.Sprintf("Config file OK: %s", configPath),
			})
		}
	} else {
		// Non-destructive: create a default config so subsequent runs pass.
		if DirExists(piHome) {
			if writeErr := os.WriteFile(configPath, []byte(defaultConfigYAML), 0o644); writeErr == nil {
				result.Issues = append(result.Issues, Issue{
					Severity: "info",
					Message:  fmt.Sprintf("Config file created with defaults: %s", configPath),
				})
			} else {
				result.Issues = append(result.Issues, Issue{
					Severity:       "warning",
					Message:        "Config file missing and could not be created",
					Recommendation: fmt.Sprintf("Create %s manually", configPath),
				})
			}
		} else {
			result.Issues = append(result.Issues, Issue{
				Severity:       "info",
				Message:        "No config file (using built-in defaults)",
				Recommendation: "Run 'pi system status' to initialize",
			})
		}
	}

	// ── Filesystem permissions ─────────────────────────────────────────────
	if DirExists(piHome) {
		info, err := os.Stat(piHome)
		if err == nil {
			perm := info.Mode().Perm()
			if perm&0o444 == 0 {
				result.Issues = append(result.Issues, Issue{
					Severity:       "warning",
					Message:        "Pi Box home directory is not readable",
					Recommendation: fmt.Sprintf("chmod 755 %s", piHome),
				})
			} else {
				result.Issues = append(result.Issues, Issue{
					Severity: "info",
					Message:  "Filesystem permissions OK",
				})
			}
		}
	}

	// ── System commands ────────────────────────────────────────────────────
	// AC-16: validate all system commands pi-sandbox relies on.
	for _, sc := range requiredSystemCommands {
		if _, err := exec.LookPath(sc.cmd); err == nil {
			result.Issues = append(result.Issues, Issue{
				Severity: "info",
				Message:  fmt.Sprintf("Command available: %s (%s)", sc.cmd, sc.what),
			})
		} else {
			result.Issues = append(result.Issues, Issue{
				Severity:       "warning",
				Message:        fmt.Sprintf("Command not found: %s (%s)", sc.cmd, sc.what),
				Recommendation: fmt.Sprintf("Install %s to enable %s", sc.cmd, sc.what),
			})
		}
	}

	// ── Daemon binary ──────────────────────────────────────────────────────
	// Warning (not error) — the daemon may be running even if not on PATH.
	if _, err := exec.LookPath("pi-sandboxd"); err == nil {
		result.Issues = append(result.Issues, Issue{
			Severity: "info",
			Message:  "pi-sandboxd binary found on PATH",
		})
	} else {
		result.Issues = append(result.Issues, Issue{
			Severity:       "warning",
			Message:        "pi-sandboxd not found on PATH",
			Recommendation: "Build with 'go build ./cmd/pi-sandboxd' and add to PATH, or start via 'pi system start'",
		})
	}

	// ── Runtime backends ───────────────────────────────────────────────────
	available := detect.AvailableRuntimes("")
	if len(available) > 0 {
		result.Issues = append(result.Issues, Issue{
			Severity: "info",
			Message:  fmt.Sprintf("Available runtime backends: %s", available),
		})
		result.Issues = append(result.Issues, Issue{
			Severity: "info",
			Message:  fmt.Sprintf("Best available mode: %s", detect.BestMode("")),
		})
	} else {
		result.Issues = append(result.Issues, Issue{
			Severity:       "error",
			Message:        "No runtime backend available",
			Recommendation: "Install gVisor (runsc) for secure mode, Docker/Podman for compat mode, or ensure Linux namespaces for fast mode",
		})
	}

	// Determine overall pass/fail.
	result.Passed = true
	for _, issue := range result.Issues {
		if issue.Severity == "error" {
			result.Passed = false
		}
	}
	return result
}

// PrintDoctor prints the doctor results in a human-readable format.
func PrintDoctor(result *DoctorResult) {
	fmt.Println("=== pi-sandbox Doctor ===")
	fmt.Println()

	status := "OK"
	if !result.Passed {
		status = "ISSUES FOUND"
	}
	fmt.Printf("Status: %s\n\n", status)

	for _, issue := range result.Issues {
		switch issue.Severity {
		case "error":
			fmt.Printf("  [ERROR]   %s\n", issue.Message)
		case "warning":
			fmt.Printf("  [WARNING] %s\n", issue.Message)
		default:
			fmt.Printf("  [OK]      %s\n", issue.Message)
		}
		if issue.Recommendation != "" {
			fmt.Printf("            -> %s\n", issue.Recommendation)
		}
	}
	fmt.Println()
}
