import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Folder structure under docs/ drives the sidebar. Add a page by dropping a
// .md file in the right folder; add a top-level category with a
// _category_.json.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
